### ISSUE TITLE
Export not working

### ISSUE THREAD

**Issue by faif** [oakes/dynadoc-examples#1]
Hi Zach. Great project 👍 

I can't get export to work. I managed to do it only once a few days ago but I don't remember what I did...

Using the basic-lein-cljs,  I'm getting this message: "You built Dynadoc with :optimizations set to :none
You must set it to :simple in order to export". I tried setting the :optimizations value to :simple both in the dev and the prod section of :cljsbuild (`project.clj`) but no luck.

Not sure if it's relevant, but when I execute lein figwheel prod it gives me the error "the build :optimizations key is set to something other than :none". Don't know much about figwheel, Is it possible to use it in production mode?

dynadoc version: 1.4.0

Any hints?

**Comment by oakes** [comment]
You can just run `lein cljsbuild once prod` in that project to get a build that can export. Let me know if you still have issues after that.

**Comment by faif** [comment]
Just tried on a clean checkout and it works fine. I must have done something wrong to my copy... Thanks 👍

**Comment by oakes** [comment]
Ah yes, with lein you may need to do "lein clean" to remove the files figwheel made.
